In [33]:
import pandas as pd
import os
from mysql import connector as cnn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from dotenv import load_dotenv
load_dotenv()
db_pass=os.getenv("DB_PASSWORD")
db=os.getenv("DB")
conn=cnn.connect(
    host='localhost',
    user='root',
    password=db_pass,
    database=db
)
cur=conn.cursor()
cur.execute("USE STUDENT")
df=pd.read_sql("SELECT * FROM ACAD_PERF",con=conn)
df

C:\Users\chait\AppData\Local\Temp\ipykernel_13560\2528743210.py:18: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql("SELECT * FROM ACAD_PERF",con=conn)


,ST_ID,PREV_GPA,ATTENDANCE,INTERNALS,BACKLOGS,STUDY_HRS_PER_WEEK,CURRENT_COURSE_LOAD,ACADEMIC_RISK
0,1,8.0,76.0,77.0,0,11.0,6,14.0
1,2,7.0,95.0,69.0,0,12.0,5,21.0
2,3,8.0,70.0,76.0,0,11.0,6,18.0
3,4,9.0,68.0,85.0,0,17.0,7,21.0
4,5,7.0,72.0,81.0,0,14.0,8,71.0
...,...,...,...,...,...,...,...,...
795,796,8.0,61.0,64.0,0,16.0,4,20.0
796,797,7.0,67.0,80.0,1,13.0,5,85.0
797,798,8.0,66.0,75.0,0,6.0,7,35.0
798,799,7.0,81.0,70.0,0,16.0,8,26.0


In [34]:
x=df.drop(columns=['ST_ID','ACADEMIC_RISK'])
y=df['ACADEMIC_RISK']
x

,PREV_GPA,ATTENDANCE,INTERNALS,BACKLOGS,STUDY_HRS_PER_WEEK,CURRENT_COURSE_LOAD
0,8.0,76.0,77.0,0,11.0,6
1,7.0,95.0,69.0,0,12.0,5
2,8.0,70.0,76.0,0,11.0,6
3,9.0,68.0,85.0,0,17.0,7
4,7.0,72.0,81.0,0,14.0,8
...,...,...,...,...,...,...
795,8.0,61.0,64.0,0,16.0,4
796,7.0,67.0,80.0,1,13.0,5
797,8.0,66.0,75.0,0,6.0,7
798,7.0,81.0,70.0,0,16.0,8


In [35]:
y

0      14.0
1      21.0
2      18.0
3      21.0
4      71.0
       ... 
795    20.0
796    85.0
797    35.0
798    26.0
799    18.0
Name: ACADEMIC_RISK, Length: 800, dtype: float64

In [36]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
x_train

,PREV_GPA,ATTENDANCE,INTERNALS,BACKLOGS,STUDY_HRS_PER_WEEK,CURRENT_COURSE_LOAD
257,6.0,75.0,77.0,1,9.0,6
650,9.0,77.0,84.0,0,9.0,5
186,8.0,74.0,74.0,0,12.0,7
23,6.0,70.0,54.0,2,14.0,5
275,8.0,95.0,59.0,0,7.0,6
...,...,...,...,...,...,...
508,7.0,74.0,74.0,0,15.0,5
582,8.0,76.0,96.0,0,3.0,4
567,6.0,63.0,51.0,1,11.0,7
719,7.0,65.0,94.0,0,12.0,5


In [37]:
y_train

257    82.0
650    29.0
186    32.0
23     84.0
275    68.0
       ... 
508    20.0
582    34.0
567    94.0
719    25.0
121    84.0
Name: ACADEMIC_RISK, Length: 640, dtype: float64

In [38]:
#Without scaling data and removing outliers
model1=LinearRegression()
model1.fit(x_train,y_train)
pred1=model1.predict(x_test)
print(pred1.shape,y_test.shape)
print(model1.score(x_test,y_test))
pred1

(160,) (160,)
0.5202912826798738


array([ 41.73812065,  43.90250237,  62.19908803,  50.93935047,
        74.20096922,  58.93767187,  12.01174025,  86.50636245,
        93.04218665,  43.42178958,  44.9925897 ,  73.35685135,
        30.44483672,  33.29206221,  62.05235597,  36.61547599,
        52.81711965,  16.00883289,  40.57734057,  85.3843548 ,
        44.15132365,  67.33037231,  36.35930718,  25.11960479,
        66.81762178,  54.18374911,  47.69707865,  81.92648937,
        56.89813338,  36.74991526,  33.48323374,  66.4568234 ,
        36.54089873,  22.19924293,  76.19272479,  73.6107585 ,
        50.45472207,  93.77609528,  54.37939193,  27.59911965,
        43.53978987,  55.58272441,  89.82474623,  60.1226371 ,
        76.14389839,  16.22078081,  50.39492721,  37.40898757,
        55.46475295,  57.61891166,  44.74988235,   7.8474635 ,
        69.20152356,  43.11402642,  66.44647218,  45.82350628,
        81.39346947,  34.26012187,  81.13471983,  36.28475012,
         8.09237183,  15.63858613,  71.70546494,  49.59

In [39]:
#With scaling and removing outliers
df.describe()

,ST_ID,PREV_GPA,ATTENDANCE,INTERNALS,BACKLOGS,STUDY_HRS_PER_WEEK,CURRENT_COURSE_LOAD,ACADEMIC_RISK
count,800.0000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000
mean,400.5000,7.193750,78.067500,71.998750,0.611250,11.941250,6.031250,51.870000
std,231.0844,1.145798,11.298563,14.158985,0.849132,5.041534,1.261849,29.391417
min,1.0000,4.000000,42.000000,32.000000,0.000000,2.000000,3.000000,4.000000
25%,200.7500,6.000000,71.000000,62.000000,0.000000,8.000000,5.000000,23.000000
50%,400.5000,7.000000,78.000000,72.000000,0.000000,12.000000,6.000000,54.000000
75%,600.2500,8.000000,86.000000,82.000000,1.000000,15.000000,7.000000,80.000000
max,800.0000,10.000000,100.000000,98.000000,4.000000,28.000000,9.000000,97.000000


In [40]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   ST_ID                800 non-null    int64  
 1   PREV_GPA             800 non-null    float64
 2   ATTENDANCE           800 non-null    float64
 3   INTERNALS            800 non-null    float64
 4   BACKLOGS             800 non-null    int64  
 5   STUDY_HRS_PER_WEEK   800 non-null    float64
 6   CURRENT_COURSE_LOAD  800 non-null    int64  
 7   ACADEMIC_RISK        800 non-null    float64
dtypes: float64(5), int64(3)
memory usage: 50.1 KB


In [41]:
#Scaling
import numpy as np
from sklearn.preprocessing import MinMaxScaler,StandardScaler
model2=LinearRegression()
scale_x=MinMaxScaler()
scale_y=MinMaxScaler()
x_train_scaled=scale_x.fit_transform(x_train)
y_train_scaled=scale_y.fit_transform(np.array(y_train).reshape(-1,1))
x_test_scaled=scale_x.transform(x_test)
y_test_scaled=scale_y.transform(np.array(y_test).reshape(-1,1))

In [42]:
#Training
model2.fit(x_train_scaled,y_train_scaled)
pred2=model2.predict(x_test_scaled)
pred2=scale_y.inverse_transform(np.array(pred2).reshape(-1,1))

In [43]:
#output
print(model2.score(x_test_scaled,y_test_scaled))
pred2

0.5202912826798733


array([[ 41.73812065],
       [ 43.90250237],
       [ 62.19908803],
       [ 50.93935047],
       [ 74.20096922],
       [ 58.93767187],
       [ 12.01174025],
       [ 86.50636245],
       [ 93.04218665],
       [ 43.42178958],
       [ 44.9925897 ],
       [ 73.35685135],
       [ 30.44483672],
       [ 33.29206221],
       [ 62.05235597],
       [ 36.61547599],
       [ 52.81711965],
       [ 16.00883289],
       [ 40.57734057],
       [ 85.3843548 ],
       [ 44.15132365],
       [ 67.33037231],
       [ 36.35930718],
       [ 25.11960479],
       [ 66.81762178],
       [ 54.18374911],
       [ 47.69707865],
       [ 81.92648937],
       [ 56.89813338],
       [ 36.74991526],
       [ 33.48323374],
       [ 66.4568234 ],
       [ 36.54089873],
       [ 22.19924293],
       [ 76.19272479],
       [ 73.6107585 ],
       [ 50.45472207],
       [ 93.77609528],
       [ 54.37939193],
       [ 27.59911965],
       [ 43.53978987],
       [ 55.58272441],
       [ 89.82474623],
       [ 60

In [44]:
from sklearn.metrics import root_mean_squared_error
print(root_mean_squared_error(y_test,pred1))

20.21029969142414


In [45]:
print(root_mean_squared_error(y_test,pred2))

20.210299691424144


In [46]:
pred1-pred2

array([[-2.84217094e-14,  2.16438171e+00,  2.04609674e+01, ...,
        -2.08644977e+01, -3.52401760e-01, -4.81337045e+00],
       [-2.16438171e+00, -7.10542736e-15,  1.82965857e+01, ...,
        -2.30288794e+01, -2.51678347e+00, -6.97775217e+00],
       [-2.04609674e+01, -1.82965857e+01,  7.10542736e-15, ...,
        -4.13254651e+01, -2.08133691e+01, -2.52743378e+01],
       ...,
       [ 2.08644977e+01,  2.30288794e+01,  4.13254651e+01, ...,
         3.90798505e-14,  2.05120959e+01,  1.60511272e+01],
       [ 3.52401760e-01,  2.51678347e+00,  2.08133691e+01, ...,
        -2.05120959e+01, -7.10542736e-15, -4.46096869e+00],
       [ 4.81337045e+00,  6.97775217e+00,  2.52743378e+01, ...,
        -1.60511272e+01,  4.46096869e+00,  3.55271368e-14]],
      shape=(160, 160))

In [47]:
import joblib as jb
jb.dump(model1,'model1.pkl')

['model1.pkl']